spring:
  datasource:
    url: jdbc:mysql://localhost:3307/demo?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 8.142.97.132
    port: 6379
    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启日志的支持er
  mapper-locations:  classpath*:/mapper/**/*.xml

server:
  port: 8888